/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_StandAloneApp
#define _Included_StandAloneApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StandAloneApp_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
